apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: redis
    name: redis
  spec:
    clusterIP: None
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis
    sessionAffinity: None
    type: ClusterIP
    publishNotReadyAddresses: true
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: redis
    labels:
      app: redis
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: redis
    serviceName: redis
    template:
      metadata:
        labels:
          app: redis
        creationTimestamp: null
      spec:
        containers:
        - name: redis
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 512Mi
          image: redis:latest
          ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}

kind: List
metadata: {}