name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: build frontend
      run: cd ./frontend && npm install && npm run build:prod && cd ..
    - name: Build the Docker image
      run: docker-compose -f ./docker-compose.build.yml build
    - name: Tag the Docker image
      run: docker tag slime_worker ccreater/slime-worker && docker tag slime_web ccreater/slime-server
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push the Docker image
      run:  docker push ccreater/slime-worker &&  docker push ccreater/slime-server
